#!/bin/bash

#define default configuration
POLL=true
SMP=auto
ERL_MAX_PORTS=32000
ERL_PROCESSES=250000
ERL_MAX_ETS_TABLES=1400
ERLANG_NODE=sesnmp
ROOTDIR=.

# define environment variables
SESNMP_HOME=$ROOTDIR
DATETIME=`date "+%Y%m%d-%H%M%S"`
SASL_LOG_PATH="$ROOTDIR/var/log/sesnmp_sasl.log"
ERL_CRASH_DUMP="$ROOTDIR/var/log/erl_crash_$DATETIME.dump"
SESNMP_SO_PATH="$ROOTDIR/priv/$ARCHDIR/lib"
SESNMP_CONFIG_PATH="$ROOTDIR/etc/sesnmp/sesnmp"

# export global variables
export SESNMP_HOME
export SESNMP_SO_PATH
export SASL_LOG_PATH
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES
export ERL_CRASH_DUMP

erl -smp $SMP +P $ERL_PROCESSES +K $POLL -sname $ERLANG_NODE -pa $ROOTDIR/ebin -config $SESNMP_CONFIG_PATH -boot start_sasl 
